// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Custom textbook sidebar
  textbook: [
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'modules/ros2-fundamentals/ros2-architecture',
        'modules/ros2-fundamentals/rclpy-control',
        'modules/ros2-fundamentals/urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'modules/digital-twin-sim/gazebo-physics-simulation',
        'modules/digital-twin-sim/sensor-simulation',
        'modules/digital-twin-sim/unity-visualization',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'modules/ai-robot-brain/isaac-sim-overview',
        'modules/ai-robot-brain/isaac-ros-perception',
        'modules/ai-robot-brain/nav2-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: The Conversational Interface (VLA)',
      items: [
        'modules/vision-language-action/01-voice-to-action',
        'modules/vision-language-action/02-language-guided-planning',
        'modules/vision-language-action/03-capstone-autonomous-humanoid',
      ],
    }
  ]
};

export default sidebars;
